# Numpy

- Numpy is a linear algebra linrary for python, the reason it is so important for Data Science with python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

- Numpy is also incrdibly fast, as it has bindings to C libraries.

- It is highly recommended youinstall python using the Anaconda distribution to make sure all underlying dependencies all sync up with the use of a conda install 

- if you have install NumPy by going to your terminal or command prompt and typing: 
```
conda install numpy
pip install numpy
```
- Numpy arrays are the main way we will use Numpy throughout the course 
- Numpy arrays are essential of 2 types: Vectors and matrices 
- Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Numpy Arrays

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [6]:
arr = np.array(my_list)

In [7]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(0,5,10) #evenly spaced points 

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
# Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# random numbers 
# 1-D
np.random.rand(5)

array([0.8495827 , 0.91516804, 0.68725474, 0.38363783, 0.07835783])

In [27]:
# 2-D
np.random.rand(5,5)

array([[0.41020515, 0.43087666, 0.67261054, 0.63559941, 0.3015462 ],
       [0.39470108, 0.47692033, 0.83094718, 0.32136134, 0.15853292],
       [0.20829594, 0.19466679, 0.6248072 , 0.79630558, 0.11515803],
       [0.338364  , 0.01469672, 0.73641677, 0.19546351, 0.66961221],
       [0.95393848, 0.54999661, 0.63020725, 0.70770501, 0.51605022]])

In [29]:
np.random.randn(4,4) # Standard normal distribution curve

array([[ 1.13199994,  0.51025698,  0.58824869,  0.01550214],
       [-2.67010314,  0.32206953, -0.63497692, -0.13114567],
       [ 0.8494615 , -0.18803042,  0.69733094,  1.68240071],
       [ 0.85744854, -0.66780245,  0.20998102, -0.36413967]])

In [31]:
np.random.randint(1,100,10)

array([22, 73, 57, 90, 63, 46, 18, 55, 61, 12])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
randarr = np.random.randint(0,50,10)

In [35]:
randarr

array([10,  7, 21, 29, 15, 34, 38, 11, 48, 33])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
randarr.max()

48

In [41]:
randarr.min()

7

In [42]:
randarr.argmax()

8

In [43]:
randarr.argmin()

1

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.shape

(5, 5)

In [48]:
arr.dtype

dtype('int32')

In [49]:
from numpy.random import randint

In [50]:
randint(2,10)

4

## Numpy Indexing and Selection

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[8]

8

In [54]:
arr[1:5]

array([1, 2, 3, 4])

In [55]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [56]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [57]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [59]:
arr[0:5] = 100

In [60]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [62]:
arr = np.arange(0,11)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
slice_of_arr = arr[:6]

In [65]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:] = 99 # Broadcasting 

In [67]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [68]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
arr_copy = arr.copy()

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [72]:
arr_copy[:] = 100

In [73]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [76]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [77]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d[0][0]

5

In [79]:
arr_2d[1][1]

25

In [81]:
arr_2d[2,1]

40

In [82]:
arr_2d[1,2]

30

In [83]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [86]:
arr = np.arange(1,11) #conditional selection

In [87]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr = arr > 5

In [90]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [91]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr < 3] #very important get used to it

array([1, 2])

In [94]:
arr_2d = np.arange(50).reshape(5,10)

In [95]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## NumPy Operations
- Array with Array
- Array with Scalars
- Universal Array Functions

In [98]:
arr = np.arange(0,11)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [101]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [102]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [103]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [104]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [105]:
1/0

ZeroDivisionError: division by zero

In [106]:
arr / arr

<ipython-input-106-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [107]:
1 / arr

<ipython-input-107-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [108]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [109]:
# Universal array functions

In [110]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [111]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [112]:
np.max(arr)

10

In [113]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [114]:
np.log(arr)

<ipython-input-114-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Create an array of 10 zeros 

In [116]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [117]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [120]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [121]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [122]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [123]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [125]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [131]:
np.random.rand(1)

array([0.32849242])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [132]:
np.random.randn(25)

array([ 0.12289223,  0.5464438 ,  1.25770855, -0.45727435,  0.09503712,
        1.10416678,  1.19447955, -0.09604231,  0.34745259,  0.59606142,
        1.41319866,  0.43521669,  0.07547142,  0.64109372,  0.81759276,
       -1.77578775, -0.937302  ,  0.62809768, -1.29531513,  0.95855809,
       -0.06705094, -0.07492183, -1.15722202, -1.30220289, -0.00525828])

#### Create the following matrix:
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [136]:
np.arange(1,101)/100

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [143]:
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [144]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [146]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE 
# array([[12, 13, 14, 15],
#        [17, 18, 19, 20],
#        [22, 23, 24, 25]])

In [148]:
mat[2:, 1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [149]:
# 20

In [151]:
mat[3,4]

20

In [152]:
# array([[ 2],
#        [ 7],
#        [12]])

In [154]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [155]:
# array([21, 22, 23, 24, 25])

In [156]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [157]:
# array([[16, 17, 18, 19, 20],
# [21, 22, 23, 24, 25]])

In [158]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [159]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [160]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [163]:
np.sum(mat,axis=0) #column sum

array([55, 60, 65, 70, 75])